// PROGRESS TAB — Weekly insight card + days logged this week
// Shows:
//   - Days logged this week (Mon–Sun, resets every Monday) — NOT a streak
//   - Weekly insight card (generated by AI, purple background)
//   - Requires 4+ days of check-in data to show insight
//   - "Generate insight" button triggers Supabase Edge Function /insight
// NO streak counter anywhere on this screen.

import { useEffect, useState } from "react";
import { View, Text, ScrollView, ActivityIndicator } from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { supabase } from "@/lib/supabase";
import InsightCard from "@/components/progress/InsightCard";
import PrimaryButton from "@/components/shared/PrimaryButton";
import LoadingDots from "@/components/shared/LoadingDots";
import { getWeekStart, getWeekEnd } from "@/lib/utils";

export default function ProgressScreen() {
  const insets = useSafeAreaInsets();
  const [daysLoggedThisWeek, setDaysLoggedThisWeek] = useState(0);
  const [insight, setInsight] = useState<any>(null);
  const [pageLoading, setPageLoading] = useState(true);
  const [generatingInsight, setGeneratingInsight] = useState(false);
  const [insufficientData, setInsufficientData] = useState(false);

  useEffect(() => {
    loadProgress();
  }, []);

  async function loadProgress() {
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) return;

    const weekStart = getWeekStart();
    const weekEnd = getWeekEnd();

    const [{ data: weekCheckins }, { data: latestInsight }] = await Promise.all([
      supabase.from("checkins").select("date").eq("user_id", user.id).gte("date", weekStart).lte("date", weekEnd),
      supabase.from("coach_messages").select("*").eq("user_id", user.id).eq("message_type", "insight").order("created_at", { ascending: false }).limit(1).single(),
    ]);

    setDaysLoggedThisWeek(weekCheckins?.length ?? 0);
    if (latestInsight) setInsight(latestInsight);
    setPageLoading(false);
  }

  async function handleGenerateInsight() {
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) return;

    setGeneratingInsight(true);
    const res = await fetch(`${process.env.EXPO_PUBLIC_SUPABASE_URL}/functions/v1/insight`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Authorization": `Bearer ${process.env.EXPO_PUBLIC_SUPABASE_ANON_KEY}`,
      },
      body: JSON.stringify({ userId: user.id }),
    });

    if (res.ok) {
      const data = await res.json();
      if (data.has_insight === false) {
        setInsufficientData(true);
      } else {
        setInsight({ content: JSON.stringify(data) });
      }
    }
    setGeneratingInsight(false);
  }

  if (pageLoading) {
    return (
      <View className="flex-1 items-center justify-center bg-background">
        <ActivityIndicator color="#1D9E75" />
      </View>
    );
  }

  const DAYS = ["M", "T", "W", "T", "F", "S", "S"];

  return (
    <ScrollView
      className="flex-1 bg-background"
      contentContainerStyle={{ paddingTop: insets.top + 16, paddingBottom: insets.bottom + 24, paddingHorizontal: 16 }}
    >
      <Text className="text-[22px] font-medium text-textPrimary mb-1">Progress</Text>
      <Text className="text-base text-textSecondary mb-6">This week, Mon–Sun</Text>

      <View className="bg-card rounded-xl p-4 mb-6">
        <Text className="text-xs font-medium uppercase tracking-widest text-textSecondary mb-3">
          Days logged this week
        </Text>
        <View className="flex-row justify-between mb-3">
          {DAYS.map((d, i) => (
            <View key={i} className="items-center">
              <View className={`w-8 h-8 rounded-full items-center justify-center mb-1 ${i < daysLoggedThisWeek ? "bg-coachGreen" : "bg-gray-100"}`}>
                <Text className={`text-xs font-medium ${i < daysLoggedThisWeek ? "text-white" : "text-textSecondary"}`}>{d}</Text>
              </View>
            </View>
          ))}
        </View>
        <Text className="text-2xl font-medium text-textPrimary">
          {daysLoggedThisWeek} <Text className="text-base font-normal text-textSecondary">of 7 days</Text>
        </Text>
      </View>

      {insight ? (
        <InsightCard insight={insight} />
      ) : (
        <View className="bg-insightPurpleBg rounded-xl p-5">
          <Text className="text-base font-medium text-insightPurple mb-2">
            Weekly Insight
          </Text>
          <Text className="text-sm text-textSecondary mb-4">
            {daysLoggedThisWeek >= 4
              ? "Your coach can analyse this week's patterns."
              : `Log ${4 - daysLoggedThisWeek} more day${4 - daysLoggedThisWeek !== 1 ? "s" : ""} to unlock your weekly insight.`}
          </Text>
          {insufficientData && (
            <Text className="text-sm text-textSecondary mb-3">
              Not enough data yet — keep going.
            </Text>
          )}
          {daysLoggedThisWeek >= 4 && !insufficientData && (
            generatingInsight ? (
              <LoadingDots />
            ) : (
              <PrimaryButton label="Generate my insight" onPress={handleGenerateInsight} />
            )
          )}
        </View>
      )}
    </ScrollView>
  );
}
